import { Grid, Text } from "@mantine/core";
import { motion } from "framer-motion";
import type { NextPage } from "next";

import Head from "next/head";
// import Link from "next/link";
import LandingLinkCard from "../components/common/landing/LandingLinkCard";

// const list = {
// 	visible: {
// 		opacity: 1,
// 		transition: {
// 			when: "beforeChildren",
// 			staggerChildren: 0.4,
// 		},
// 	},
// 	hidden: {
// 		opacity: 0,
// 		transition: {
// 			when: "afterChildren",
// 		},
// 	},
// };

// const item = {
// 	visible: { opacity: 1, x: 0, y: 0 },
// 	hidden: { opacity: 0, x: 0, y: -400 },
// };

const pageLinks: Array<LandingLink> = [
	{
		link: "/post-production",
		label: "Post Production Hub",
		background: "/images/flmaker-5110278_1920.jpg",
	},
	{
		link: "/camera-rental",
		label: "Camera Rental",
		background: "/images/flmaker-5110278_1920.jpg",
	},
	{
		link: "/production",
		label: "Production",
		background: "/images/flmaker-5110278_1920.jpg",
	},
	{
		link: "/interiors",
		label: "Home Theater",
		background: "/images/flmaker-5110278_1920.jpg",
	},
	{
		link: "http://premiumfreshfoods.com/sicf-1/",
		label: "Film Festival",
		isExternal: true,
		background: "/images/flmaker-5110278_1920.jpg",
	},
];

const Home: NextPage = () => {
	const MotionGrid = motion(Grid, { forwardMotionProps: true });
	const MotionCol = motion(Grid.Col, { forwardMotionProps: true });
	return (
		<>
			<Head>
				<title>ScreenFocus | Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="container flex flex-row items-center mx-auto mt-16 h-96">
				<section className="w-3/12">
					<Text className="font-thin capitalize text-8xl text-primary">We</Text>
					<div className="flex flex-col mt-8 space-y-4">
						<Text className="text-6xl font-bold text-dark">Deliver.</Text>
						<Text className="text-6xl font-bold text-dark">Decorate.</Text>
						<Text className="text-6xl font-bold text-dark">Organize.</Text>
					</div>
					<div className="flex flex-row mt-12 space-x-4">
						<Text className="text-4xl font-thin text-dark">Your</Text>
						<span className="w-2 h-auto bg-primary"></span>
						<Text className="text-4xl font-semibold">Projects</Text>
					</div>
				</section>
				<section className="flex flex-row justify-between w-9/12 h-full">
					{pageLinks.map((pageLink) => (
						<LandingLinkCard key={`PAGE_LINK_${pageLink.label}`} link={pageLink} />
					))}
				</section>
			</main>
		</>
	);
};

export default Home;

