import { Grid, Image } from "@mantine/core";
import { AnimatePresence, motion } from "framer-motion";
import type { NextPage } from "next";

import Head from "next/head";

const list = {
	visible: {
		opacity: 1,
		transition: {
			when: "beforeChildren",
			staggerChildren: 0.2,
		},
	},
	hidden: {
		opacity: 0,
		transition: {
			when: "afterChildren",
		},
	},
};

const item = {
	visible: { opacity: 1, x: 0, y: 0 },
	hidden: { opacity: 0, x: 0, y: -400 },
};

const Home: NextPage = () => {
	const MotionGrid = motion(Grid, { forwardMotionProps: true });
	const MotionCol = motion(Grid.Col, { forwardMotionProps: true });
	return (
		<>
			<Head>
				<title>ScreenFocus | Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<motion.div
				animate={{ opacity: 1 }}
				initial={false}
				transition={{ duration: 2,ease: "easeIn" }}
				className="my-12 w-full flex flex-col items-center select-none"
			>
				<div className="w-28 h-28 rounded-full bg-red-100 flex justify-center items-center">
					<Image width={70} alt="screen focus logo" src="/logo.svg"></Image>
				</div>
				{/* <h1 className="text-6xl text-red-400">Screen Focus</h1> */}
			</motion.div>
			<AnimatePresence>
				<MotionGrid initial="hidden" animate="visible" variants={list} className="mt-4 select-none justify-evenly">
					<MotionCol
						variants={item}
						className="bg-red-400 h-[60vh] rounded-lg shadow-xl text-center text-white"
						span={2}
					>
						Screen focus Post Production Hub
					</MotionCol>
					<MotionCol
						variants={item}
						className="bg-red-500 h-[60vh] rounded-lg shadow-xl text-center text-white"
						span={2}
					>
						Screen focus Camera Rental
					</MotionCol>
					<MotionCol
						variants={item}
						className="bg-red-600 h-[60vh] rounded-lg shadow-xl text-center text-white"
						span={2}
					>
						Screen focus Productions
					</MotionCol>
					<MotionCol
						variants={item}
						className="bg-red-700 h-[60vh] rounded-lg shadow-xl text-center text-white"
						span={2}
					>
						Screen focus Home Theater & Studio Interiors
					</MotionCol>
					<MotionCol
						variants={item}
						className="bg-red-800 h-[60vh] rounded-lg shadow-xl text-center text-white"
						span={2}
					>
						Screen focus Film Festival & Awards
					</MotionCol>
				</MotionGrid>
			</AnimatePresence>
		</>
	);
};

export default Home;

